spring.application.name=authentication

# PostgreSQL (Neon)
spring.datasource.url=jdbc:postgresql://ep-damp-band-a1yek0ly-pooler.ap-southeast-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_itHN2VuQ9MXE

# Driver
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# JWT
jwt.secret=my_super_secret_key_for_jwt_authentication_system_2026
jwt.access-token-expiration=900000
jwt.refresh-token-expiration=604800000